AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs10.x
      Policies:
      - Statement:
        - Sid: CreateCloudWatchLogsPolicy
          Effect: Allow
          Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents        
          Resource: '*'
        - Sid: DescribeCodeCommitPolicy
          Effect: Allow
          Action:
          - codecommit:GetCommit
          - codecommit:ListBranches
          - codecommit:GetComment
          - codecommit:GetCommitHistory
          Resource: '*'            
